[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nikos-safebooru-wrapper"
version = "1.0.4"
description = "A Python wrapper for the safebooru.org API"
authors = [
    {name = "Niko"}
]
dependencies = [
    "requests",
    "httpx",
    "python-dotenv",
    "pydantic",
    "python-magic",
    "beautifulsoup4",
    "lxml",
    "platformdirs",
]
license = {text = "Unlicense"}
readme = "README.md"

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
rule34 = "rule34.__main__:main"